### ISSUE TITLE
InvalidArgumentError in Categorical distribution

### ISSUE THREAD

**Issue by ioannanikolopoulou** [NF4HEP/NormalizingFlowsHD#1]
In the file MixtureDistributions.py in lines 72 and 100 the probabilities in the categorical distribution don't sum up to 1. You can check this by adding the argument "validate_args=True":

cat=tfd.Categorical(probs=probs, validate_args=True)

This throws an error message.

Does this affect the validity of the simulations?

**Comment by hreyes91** [comment]
Hi!,

This is not a problem, the validity of the simulations are not affected. Here, the rol of the categorial distribution is just to assing 'weights' to each mode in the multi-modal distributions. For each MoG distributions, their parameters remain fixed trough all the study.

**Comment by ioannanikolopoulou** [comment]
Thank you, 

It is good to know that the simulations are not affected by that. Regardless the 'weights', it might be a good idea to sample from a Dirichlet distribution.
